version: "3.9"

services:
  api:
    build:
      context: .
      target: "production"
    image: mighty-agent-backend
    container_name: mighty-agent-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    env_file:
      - .env
